### ISSUE TITLE
wrong version error

### ISSUE THREAD

**Issue by qingyiyi** [szcompressor/SZ#115]
I was successfully running SZ on my old server but recently I switched to a new server and the same code is retaining such an error for some reason, I don't know what compressed-data version means, can you help me? the error is as follows：
wrong version:
compressed-data version(0.0. -128)
current sz version: (2.1.12)
please double-check if the compressed data (or file) is correct.

**Comment by robertu94** [comment]
Was the data compressed with an earlier version of SZ?  This will help us identify and fix the issue.

**Comment by disheng222** [comment]
Yes. Robert raised a good question. Please make sure you are using the same
version of the compressor to do the compression and decompression.

**Comment by qingyiyi** [comment]
I used the 2.1.12.2 version of the compressor for the compression and decompression process, which does not involve other versions of the compressor.

**Comment by disheng222** [comment]
Can I see you commands?

Sent from my iPhone


qingyiyi ***@***.***>于2023年9月21日 周四下午6:21写道：

**Comment by qingyiyi** [comment]
The core code for compression is as follows
      size_t szsize;
      unsigned char* bytes = use_sz_compress(d1,trace_length,&szsize,error_bound);
      result += szsize;
      float* data = use_sz_decompress(trace_length,&bytes,szsize);
Among them, d1 is the array to be compressed, use_sz_compress and use_sz_decompress are my own encapsulated functions, the specific implementation is as follows
      unsigned char* use_sz_compress(float* data, int datasize, size_t* szsize, double error_bound)
      {
      size_t r5 = 0; size_t r4 = 0; size_t r3 = 0; size_t r2 = 0; size_t r1 = datasize;
      unsigned char* bytes = SZ_compress_args(SZ_FLOAT, data, szsize, PW_REL, error_bound, error_bound, error_bound, r5, r4, r3, r2, r1);
      return bytes;
      }
      
      float* use_sz_decompress(int datasize,unsigned char** bytes, size_t szsize)
      {
      size_t r5 = 0; size_t r4 = 0; size_t r3 = 0; size_t r2 = 0; size_t r1 = datasize;
      float* data = (float*)malloc(datasize * sizeof(float));
      SZ_decompress_args(SZ_FLOAT, *bytes, szsize, data, r5, r4, r3, r2, r1);
      return data;
      }
This code works fine on my old server

**Comment by qingyiyi** [comment]
I am using compression in a program. The core code for compression is as follows
```
char *Path="./SZ-2.1.12.2/example/sz.config";
SZ_Init(Path);
size_t szsize;
unsigned char* bytes = use_sz_compress(d1,trace_length,&szsize,error_bound);
result += szsize;
float* data = use_sz_decompress(trace_length,&bytes,szsize);
```
Among them, d1 is the array to be compressed, use_sz_compress and use_sz_decompress are my own encapsulated functions, the specific implementation is as follows
```
unsigned char* use_sz_compress(float* data, int datasize, size_t* szsize, double error_bound)
{
size_t r5 = 0; size_t r4 = 0; size_t r3 = 0; size_t r2 = 0; size_t r1 = datasize;
unsigned char* bytes = SZ_compress_args(SZ_FLOAT, data, szsize, PW_REL, error_bound, error_bound, error_bound, r5, r4, r3, r2, r1);
return bytes;
}
float* use_sz_decompress(int datasize,unsigned char** bytes, size_t szsize)
{
size_t r5 = 0; size_t r4 = 0; size_t r3 = 0; size_t r2 = 0; size_t r1 = datasize;
float* data = (float*)malloc(datasize * sizeof(float));
SZ_decompress_args(SZ_FLOAT, *bytes, szsize, data, r5, r4, r3, r2, r1);
return data;
}
```
This code works fine on my old server

**Comment by disheng222** [comment]
Hi,
I tested your code, but I didn't encounter that issue. The decompressed
data also respect the error bound PW_REL = 1E-2 in my test.
I changed your function a bit. For decompression, you don't need to use
unsigned char** bytes. Unsigned char* bytes is enough. Please see the
attached file: testfloat_compress.c. You can replace the
testfloat_compress.c in the examples/ directory and rebuild it by running
make in the directory example/. I got the following results:
***@***.*** example]$ ./testfloat_compress sz.config
testdata/x86/testfloat_8_8_128.dat
cfgFile=sz.config
timecost=0.002530
done
***@***.*** example]$ compareData -f testdata/x86/testfloat_8_8_128.dat
testdata/x86/testfloat_8_8_128.dat.sz.out
This is little-endian system.
reading data from testdata/x86/testfloat_8_8_128.dat
Min = 0.21328493952751159668, Max = 5.0532207489013671875, range =
4.8399358093738555908
Max absolute error = 0.0042190552
Max relative error = 0.000872
Max pw relative error = 0.000987
PSNR = 74.444675, NRMSE = 0.00018956852791261136963
normErr = 0.083043, normErr_norm = 0.000578
pearson coeff = 1.000000

(The compareData command can be found in qcat:
https://github.com/szcompressor/qcat, after you install it.)

**Comment by qingyiyi** [comment]
Okay, thank you very much.
