### ISSUE TITLE
Error bound rate

### ISSUE THREAD

**Issue by mearcla** [szcompressor/SZ#118]
Hello,
 please, I need to understand the relation between the value of error bound and the compression rate. what is the difference between using 0.5,0.005 or set the error bound = Zero ?
is there any paper that explain that?

**Comment by disheng222** [comment]
SZ is a lossy compressor. Please don't set error bound to zero. We didn't test this case, which may cause unexpected result I guess. Using different error bounds means the reconstructed data after running the compression and decompression will have different levels of data distortion. 0.005 means the difference between original data vs. reconstructed data will be always within the 0.005. So, 0.5 means much worse quality of reconstructed data after decompression. However 0.5 will make the compression have a higher compression ratio than 0.005 does. You asked a question regarding the basic concept about error bound. You can check this paper for more details: Dingwen Tao, Sheng Di, Hanqi Guo, Zizhong Chen, and Franck Cappello, "Z-checker: A Framework for Assessing Lossy Compression of Scientific Data", in The International Journal of High Performance Computing Applications (IJHPCA), 2017

**Comment by mearcla** [comment]
I have another question please, how can I get on the size of uncompressed data? 

float *uncompdata = (float*) SZ_decompress(SZ_FLOAT, bytes, byteLength, r5, r4, r3, r2, r1);

**Comment by disheng222** [comment]
The size of uncompressed data should be the same as that of the original
dataset. It's preknown. Or, you can compute it based on the dimensions, r5,
r4, ..., r1.

Best,
Sheng
