### ISSUE TITLE
API is not thread-safe

### ISSUE THREAD

**Issue by martinradev** [szcompressor/SZ#29]
The compress and decompress functions are not thread-safe. The reason for this is that a global context ```confparams_cpr```, ```confparams_dec```, ```exe_params``` is modified via some of the calls. Example:
```
unsigned char* SZ_compress_args(int dataType, void *data, size_t *outSize, int errBoundMode, double absErrBound, 
double relBoundRatio, double pwrBoundRatio, size_t r5, size_t r4, size_t r3, size_t r2, size_t r1)
{
	confparams_cpr->dataType = dataType;
```

```
void *SZ_decompress(int dataType, unsigned char *bytes, size_t byteLength, size_t r5, size_t r4, size_t r3, size_t r2, size_t r1)
{
	if(confparams_dec==NULL)
		confparams_dec = (sz_params*)malloc(sizeof(sz_params));
	memset(confparams_dec, 0, sizeof(sz_params));
	if(exe_params==NULL)
		exe_params = (sz_exedata*)malloc(sizeof(sz_exedata));
	memset(exe_params, 0, sizeof(sz_exedata));
	exe_params->SZ_SIZE_TYPE = 8;
```

I think it would be beneficial to guarantee that calling the compress/decompress is thread safe. Otherwise, the user would have to introduce a single lock for the compress / decompress paths which would lead to contention and kill multi-threaded performance.

**Comment by martinradev** [comment]
A solution would be to modify the API. Instead of keeping a global context stored in the library, the API could be extended so that ContextInit returns a context handle to the user.
The context handle is to be passed to the compress/decompress functions. The handle can additionally be bound to a mutex so that within the implementation of the compress/decompress functions, the mutex is acquired.
This achieves two things:
- calls are always thread safe
- contention is reduced as long as multiple contexts are used. A single context per thread would be a good granularity.

**Comment by disheng222** [comment]
Forgot to mention that the thread safe support is mainly provided for single-precision (float) and double-precision (double) in the current implementation.

**Comment by mrmbernardi** [comment]
Is the PSNR mode currently thread safe?
