### ISSUE TITLE
sz_omp.c:19:19: error: ‘CLOCK_MONOTONIC_RAW’ undeclared

### ISSUE THREAD

**Issue by xantares** [szcompressor/SZ#58]
it seems CLOCK_MONOTONIC_RAW is linux-specific and wont compile for win32:
```
#ifdef _OPENMP
    return omp_get_wtime();
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC_RAW, &ts);

    return (double)ts.tv_sec + (double)ts.tv_nsec / 1000000000.0;
#endif
```

**Comment by disheng222** [comment]
SZ doesn't support windows version. 
In addition to the CLOCK_MONOTONIC_RAW, I guess there might be more issues if you compile SZ on windows, e.g., some data type in SZ is declared as long which is 8 bytes on Linux but it is 4 bytes on Windows. We never tested SZ on windows. Sorry about that.
