### ISSUE TITLE
Do you have GPU/cuda version?

### ISSUE THREAD

**Issue by sheltongeosx** [szcompressor/SZ#61]
Dear SZ Developers, 

      Do you have any time line for GPU/CUDA release?

Best,
Shelton

**Comment by dingwentao** [comment]
Hi Shelton,

Yes, our CUDA version (called cuSZ) will be released by the end of September. The repo will be https://github.com/szcompressor/cuSZ. We will let you know when the repo is publicly accessible. 

Thanks,
Dingwen

**Comment by dingwentao** [comment]
> Dear SZ Developers,
> 
> ```
>   Do you have any time line for GPU/CUDA release?
> ```
> 
> Best,
> Shelton

Hi Shelton,

Yes, our CUDA version (called cuSZ) will be released by the end of September. The repo will be https://github.com/szcompressor/cuSZ. We will let you know when the repo is publicly accessible.

Thanks,
Dingwen

**Comment by dingwentao** [comment]
Dear Shelton @sheltongeosx 

cuSZ has been released at https://github.com/szcompressor/cuSZ. You're welcome to test it. Please feel free to let us know if you have any question. 

Thanks,
Dingwen
