### ISSUE TITLE
Low compression ratio on Parihaka Seismic Data

### ISSUE THREAD

**Issue by dingwentao** [szcompressor/SZ#64]
Hi @sheltongeosx @MauricioAP @jiemeng-total

I open a new thread in SZ repo (referenced to [this issue](https://github.com/szcompressor/cuSZ/issues/6) in cuSZ), so that the SZ team may help you solve the issue of the low compression ratio on your data set. 

Hi @disheng222,

Shelton faced an issue to use SZ or cuSZ to compress his seismic data. Using the value-range-based relative error bound of 1e-4 can only provide a compression ratio of about 6. The data can be downloaded [here](https://eecs.wsu.edu/~dtao/download/Parihaka_PSTM_far_stack.f32). The official SGY format data can be found [here](https://wiki.seg.org/wiki/Parihaka-3D). The data size is "-3 1168 1126 922". Do you think we can look into this?

```
$ sz -z -f -c sz.config -M REL -R 1e-4 -i /work/06128/dtao/frontera/dataset/reduction/08_SGY_922_1126_1168=1212584896/Parihaka_PSTM_far_stack.f32 -3 1168 1126 922
compression time = 38.944234 seconds
compressed data file: /work/06128/dtao/frontera/dataset/reduction/08_SGY_922_1126_1168=1212584896/Parihaka_PSTM_far_stack.f32.sz
```
```
$ sz -x -s /work/06128/dtao/frontera/dataset/reduction/08_SGY_922_1126_1168=1212584896/Parihaka_PSTM_far_stack.f32.sz -i /work/06128/dtao/frontera/dataset/reduction/08_SGY_922_1126_1168=1212584896/Parihaka_PSTM_far_stack.f32 -3 1168 1126 922 -a
Min=-6893.359375, Max=5448.8828125, range=12342.2421875
Max absolute error = 1.2342240810
Max relative error = 0.000100
Max pw relative error = 89749692.983013
PSNR = 84.876211, NRMSE= 5.7041304938182735089E-05
normError = 24515.434433, normErr_norm = 0.002501
acEff=0.999997
compressionRatio=6.210478
decompression time = 27.484778 seconds.
decompressed data file: /work/06128/dtao/frontera/dataset/reduction/08_SGY_922_1126_1168=1212584896/Parihaka_PSTM_far_stack.f32.sz.out
```

**Comment by ayzk** [comment]
Hi @sheltongeosx @MauricioAP @jiemeng-total
Will a larger error bound satisfy your application's requirements? We have a new compressor in beta that has a better compression ratio on the Parihaka dataset when the error bound is larger than 1e-3. Here are the results of the new compressor.
Error Bound    Compressor Ratio
1e-3                 13
3e-3                26
5e-3                43
8e-3                58
1e-2                 75

1E-4 on this dataset is more challenging and we don't have a solution that has a compression ratio higher than 6 yet.

**Comment by disheng222** [comment]
Hi @sheltongeosx @MauricioAP @jiemeng-total @ayzk 
We note that your dataset has very large value range (seems to be about 8000). In this case, 1E-4 will be a very high precision requirement based on our experience. That is, 1E-4 means a nearly lossless compression, because the single-precision 32-bit iEEE 754 format can only cover 4 mantisan bits. For example, 
1600.1112's representation is 01000100 11001000 00000011 10001111. 
1600.1111's representation is 01000100 11001000 00000011 10001110 . 
Only the very last bit is different.

**Comment by disheng222** [comment]
Hi @sheltongeosx @MauricioAP @jiemeng-total @ayzk 
I thought you are using absolute error bound, but after double-checking the past messages, I noted that you were using value-range based error bound, which should be appropriate. 
We are doing more experiments to assess the compression ratios.
