### ISSUE TITLE
Can lossless compression be used

### ISSUE THREAD

**Issue by lljjgg** [szcompressor/SZ#65]
SZ is Lossy Compressor.But Some compressors can provide lossless compression.for example fpzip and zfp.I want to know if sz can use lossless compression and what should I do if it can.

**Comment by disheng222** [comment]
Strictly speaking, SZ has no lossless compression mode, unlike fpzip and
zfp.
If you are setting a very small absolute error bound, it may gracefully
degrade to the simple zstd to compress the data instead.
