### ISSUE TITLE
h5repack pointer being freed was not allocated 

### ISSUE THREAD

**Issue by dbinlbl** [szcompressor/SZ#73]
Hello SZ,
When to run the h5repack code and it failed with below error.
Could anyone help to look it?

Thanks.
Bin
---------------------------
h5repack(11138,0x10bd43e00) malloc: *** error for object 0x7f926e922030: pointer being freed was not allocated
h5repack(11138,0x10bd43e00) malloc: *** set a breakpoint in malloc_error_break to debug
./h5repack.sh: line 12: 11138 Abort trap: 6           h5repack -f UD=32017,0 -i $inputFile -o $outputFile

When running it via lldb, it has below info.
-------------------------

% lldb h5repack
(lldb) run -f UD=32017,0 -i testfloat_8_8_128.h5   -o testfloat_8_8_128_sz.h5
Process 11129 launched: '/Users/dbin/work/soft/hdf5-1.12.0/build/bin/h5repack' (x86_64)
h5repack(11129,0x10013be00) malloc: *** error for object 0x101fbd030: pointer being freed was not allocated
h5repack(11129,0x10013be00) malloc: *** set a breakpoint in malloc_error_break to debug
Process 11129 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff203c1462 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff203c1462 <+10>: jae    0x7fff203c146c            ; <+20>
    0x7fff203c1464 <+12>: movq   %rax, %rdi
    0x7fff203c1467 <+15>: jmp    0x7fff203bb6a1            ; cerror_nocancel
    0x7fff203c146c <+20>: retq
Target 0: (h5repack) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff203c1462 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff203ef610 libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007fff20342720 libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff20223430 libsystem_malloc.dylib`malloc_vreport + 548
    frame #4: 0x00007fff202264c8 libsystem_malloc.dylib`malloc_report + 151
    frame #5: 0x0000000101e861b2 libhdf5sz.so`H5Z_filter_sz(flags=0, cd_nelmts=<unavailable>, cd_values=<unavailable>, nbytes=32768, buf_size=0x00007ffeefbfe378, buf=0x00007ffeefbfe420) at H5Z_SZ.c:0 [opt]
    frame #6: 0x00000001008b79dd libhdf5.200.dylib`H5Z_pipeline + 2797
    frame #7: 0x00000001002a07f2 libhdf5.200.dylib`H5D__chunk_flush_entry + 1922
    frame #8: 0x0000000100298da8 libhdf5.200.dylib`H5D__chunk_flush + 536
    frame #9: 0x00000001002e7ea8 libhdf5.200.dylib`H5D__flush_real + 616
    frame #10: 0x00000001002e6c96 libhdf5.200.dylib`H5D_close + 502
    frame #11: 0x0000000100897bd7 libhdf5.200.dylib`H5VL__native_dataset_close + 391
    frame #12: 0x0000000100862ecf libhdf5.200.dylib`H5VL__dataset_close + 703
    frame #13: 0x0000000100862af0 libhdf5.200.dylib`H5VL_dataset_close + 832
    frame #14: 0x00000001002f297b libhdf5.200.dylib`H5D__close_cb + 475
    frame #15: 0x00000001004c1911 libhdf5.200.dylib`H5I_dec_ref + 401
    frame #16: 0x00000001004c15f5 libhdf5.200.dylib`H5I_dec_app_ref + 181
    frame #17: 0x00000001004c1aa5 libhdf5.200.dylib`H5I_dec_app_ref_always_close + 181
    frame #18: 0x000000010028052d libhdf5.200.dylib`H5Dclose + 877
    frame #19: 0x000000010000fa9e h5repack`do_copy_objects + 14510
    frame #20: 0x000000010000b5d0 h5repack`copy_objects + 8416
    frame #21: 0x0000000100004685 h5repack`h5repack + 101
    frame #22: 0x000000010000191d h5repack`main + 413
    frame #23: 0x00007fff2040a621 libdyld.dylib`start + 1

**Comment by disheng222** [comment]
Hi,
I noted that H5Z-SZ cannot work normally with hdf5-1.12.0. I tested other
filters with hdf5-1.12.0, and they all work abnormally.
For other filters, the compressed data have exactly the same size as the
original .h5 data file, which obviously means that the filter was not
called correctly.
If I use the hdf5-1.10.x version, all filters (including H5Z-SZ) work very
well.
Could you use hdf5-1.10.x to try it again?

Best,
Sheng
