### ISSUE TITLE
HDF5 version hdf5-1.12.0

### ISSUE THREAD

**Issue by dbinlbl** [szcompressor/SZ#74]
Hello SZ,
Sorry that I have lots of issues here and thanks for the help to fix them.
I tried the code on the latest version of the HDF5, i.e., hdf5-1.12.0.

It reported the same error like the one in h5repack here https://github.com/szcompressor/SZ/issues/73

See below for the results from running the code with hdf5-1.12.0.

Thanks, 
Bin
========
./szToHDF5 -d sz.config ../../../example/testdata/x86/testdouble_8_8_128.dat 8 8 128

config file = sz.config
cfgFile=sz.config
output file: ../../../example/testdata/x86/testdouble_8_8_128.dat.sz.h5
Dimension sizes: n5=0, n4=0, n3=128, n2=8, n1=8
sz filter is available for encoding and decoding.
....Writing SZ compressed data.............
original data = 0.225612 0.225635 0.225691 0.225739 0.225738 0.225691 0.225623 0.225564 0.225612 0.225635 0.225691 0.225739 0.225738 0.225691 0.225623 0.225564 0.225612 0.225635 0.225691 0.225739 ....
szToHDF5(12144,0x10bee6e00) malloc: *** error for object 0x7fadd99a5030: pointer being freed was not allocated
szToHDF5(12144,0x10bee6e00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./szToHDF5 -d sz.config ../../../example/testdata/x86/testdouble_8_8_128.dat

**Comment by disheng222** [comment]
Hi Bin,
I have replied to you in another email.
I think the latest version hdf5-1.12 seems to have some bugs.
My reason is that if I use hdf5-1.12, all filters seem to work abnormally.
Specifically, after running any filter, the generated "filtered" data file
has the same size as the original .h5 data file, which doesn't make sense.
All filters (including H5Z-SZ) work normally when using the hdf5-1.10.x
version. So, I suggest using hdf5-1.10.
In fact, I know some users encountered similar issues before and they are
using hdf5-1.10 in their experiments, and everything works well for them.

Best,
Sheng

**Comment by dbinlbl** [comment]
Hi Sheng,
Thanks for clearing my confusion. 
I had both the hdf5-1.12 and hdf5-1.10.7 installed on my systems.

hdf5-1.10.7 works in all cases but sometimes I used the "h5dump/h5repack" from the hdf5-1.12, which gave this error and the one https://github.com/szcompressor/SZ/issues/73


Please help to close the tickets and thanks again.

Bests,
Bin
