### ISSUE TITLE
compiler.h file not found 

### ISSUE THREAD

**Issue by lilygeorge** [szcompressor/SZ#79]
I have error in file (fse_compress) where the compiler.h not found ??!! how can get on this file  ?

**Comment by robertu94** [comment]
@lilygeorge the file in question is likely from `zstd/common/compiler.h`.

You might try building with `spack` which will ensure that Zstd is installed properly.  Using SZ from spack can be as simple as

```
git clone https://github.com/spack/spack
source spack/share/spack/setup-env.sh
spack compiler find
spack install sz
```


I'm guessing you used the bundled version of Zstd which is the default.  Could you provide your OS version (on linux /etc/os-release), whether or not you have zstd-devel or the equivent system package installed, and the commands you used to build SZ so we can track down this bug?
