### ISSUE TITLE
Problem using SZ filter from python with h5py>=3

### ISSUE THREAD

**Issue by orioltinto** [szcompressor/SZ#81]
For the last months I've been successfully using the SZ HDF5 filter to write compressed data in netcdf format from python.
However, while it works great with h5py 2.10, with versions of h5py from 3.0 the filter does not work anymore.
This is problematic for us because we can't stuck to a h5py version because other libraries require later releases.

The specific error that is thrown by HDF5 is :

```
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: H5T.c line 1876 in H5Tget_class(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: H5E.c line 1417 in H5Epush2(): can't push error on stack
    major: Error API
    minor: Can't set value
  #001: H5I.c line 1417 in H5I_inc_ref(): can't locate ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #002: H5T.c line 1876 in H5Tget_class(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
```

The python stack:
```python
  File ".../xarray/backends/h5netcdf_.py", line 315, in prepare_variable
    nc4_var = self.ds.create_variable(
  File ".../h5netcdf/core.py", line 535, in create_variable
    return group._create_child_variable(
  File ".../h5netcdf/core.py", line 512, in _create_child_variable
    self._h5group.create_dataset(
  File ".../h5py/_hl/group.py", line 153, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File ".../h5py/_hl/dataset.py", line 134, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (error during user callback)
```

Any idea about what is happening here?

**Comment by orioltinto** [comment]
Any way of getting feedback here?

**Comment by robertu94** [comment]
@orioltinto Sheng just asked me to take a look at this.  A few things to confirm here.  Are h5py for python2 and python3 loading the same version of HDF5?  It also would be helpful to know your OS version, compiler, hdf5 and netcdf version, python version, and the version of the sz hdf5 filter plugin that you are using.

The next step would be to create a reproducer on our end.  Could you send a self-contained small code example that can demonstrate the bug?  This will help us isolate the issue on our end.

**Comment by orioltinto** [comment]
Hi @robertu94 ,
thanks for answering.

I'll prepare a reproducer.

**Comment by orioltinto** [comment]
Hi @robertu94,
your questions already guided me in the proper direction, thanks.
Somehow, with h5py<3 I could use the filters even using the precompiled h5py version. In h5py>=3 its no longer the case but installing hp5py without precompiled binaries I managed to use the filter.

I would say that now mostly works.
I have a problem using abs mode with big thresholds which writes the file without throwing errors but a segmentation fault happens when reading it. I'll write a new issue with a code to reproduce it.
