### ISSUE TITLE
1D and 2D array dimensions.

### ISSUE THREAD

**Issue by epasveer** [szcompressor/SZ#82]
A question about the api for 1D and 2D arrays.  Are these dimensions equivalent?

`r5=0 r4=0 r3=0 r2=1 r1=1000`
`r5=0 r4=0 r3=0 r2=0 r1=1000`

In both cases, I pass a 1D float array that is 1000 floats.

In the first case, it encounters a divide-by-zero FPE. Looking at the code, it seems to use the 2D case for compressing.
In the second case, it works fine.

**Comment by disheng222** [comment]
They are not equivalent to API. Please use the second way to input the
dimension.

**Comment by disheng222** [comment]
After double-checking the code, I think the way 1 should also work.
Could you send me the testing data and your example code (how you call the
API). I'll check what's going on.

**Comment by disheng222** [comment]
BTW, I recommend our improved version SZ3 (github.com/szcompressor/SZ3), which should have higher compression ratios and quality than SZ, though it may have a slightly performance degradation than SZ. Please feel free to test it. SZ3 has the same API and executable command with SZ.

**Comment by epasveer** [comment]
Cool.  I will try it out and will let you know.

**Comment by disheng222** [comment]
Hi Ernie,
SZ 2.1.11 does not support that format of dimensions.
You can use the master branch or the release 2.1.12.2, which I just
committed.
Please let me know if there are still dimension issues.

Best,
Sheng

**Comment by epasveer** [comment]
Sure. I'll try the version you just released.

**Comment by disheng222** [comment]
Hi ernie,
I didn't make any changes, because I noted that you were using sz 2.1.11,
which I am sure should have that problem.
So, I just committed a new release based on master branch as sz 2.1.12.2
which should have addressed the issue.
If you mean sz2.1.12.2 also has a problem, I will look into it further
based on your dataset.

Best,
Sheng

**Comment by epasveer** [comment]
Correct,  sz2.1.12.2 has the same problem. 

Sent from AT&T Yahoo Mail on Android 
 
  On Thu, Feb 10, 2022 at 5:28 PM, Sheng ***@***.***> wrote:   

Hi ernie,
I didn't make any changes, because I noted that you were using sz 2.1.11,
which I am sure should have that problem.
So, I just committed a new release based on master branch as sz 2.1.12.2
which should have addressed the issue.
If you mean sz2.1.12.2 also has a problem, I will look into it further
based on your dataset.

Best,
Sheng

**Comment by epasveer** [comment]
Hi Sheng,

Your latest tar ball works great.  Thanks!

I'm closing the task.
