### ISSUE TITLE
SZ principle work

### ISSUE THREAD

**Issue by mearcla** [szcompressor/SZ#94]
Is there any paper explain the principle work of the sz algorithm? 
Thanks,

**Comment by disheng222** [comment]
I forgot to mention that SZ2.1 is maintained here:
https://github.com/szcompressor/SZ3

**Comment by mearcla** [comment]
I used SZ 2.1 so I think this paper explains well about the algorithm too "Fast Error-bounded Lossy HPC Data Compression with SZ"

**Comment by disheng222** [comment]
FYI, the paper "Fast Error-bounded Lossy HPC Data Compression with SZ"
corresponds to SZ0.1, which is a deprecated version.
The paper "Significantly Improving Lossy Compression for Scientific Data
Sets Based on Multidimensional Prediction and Error-Controlled
Quantization" corresponds to the SZ1.4, which has been integrated in SZ2.1
SZ 2.1's paper is this one: Xin Liang, Sheng Di, Dingwen Tao, Sihuan Li,
Shaomeng Li, Hanqi Guo, Zizhong Chen, Franck Cappello, "Error-Controlled
Lossy Compression Optimized for High Compression Ratios of Scientific
Datasets", in *IEEE Bigdata2018*, 2018.

**Comment by mearcla** [comment]
Yes, I read it now thank you for this clarification.
What about this [SZ 2.1.12.2], please?

**Comment by disheng222** [comment]
It's in the paper published by *IEEE Bigdata2018*, 2018.
