### ISSUE TITLE
Segmentation fault when first dimension has size 1 

### ISSUE THREAD

**Issue by orioltinto** [szcompressor/SZ#95]
Dear SZ developers,

## Summary
I'm using the **HDF5 filter** to compress datasets.
In my workflow, I have to chunk one of the dimension with slices of size 1.
The problem is that when the dimension with slice size 1 is the first, a segmentation fault occurs. 

~~If the dimension of size 1 is in any other position, the segmentation fault doesn't happen.~~
**Edit:** If the dimension of size 1 is in any of the dimensions in the middle I get a `signal 7: SIGEMT`.

It is very inconvenient because most datasets have the time as the first dimension.

Is that a known bug? Is there any solution?

Any help will be appreciated.

## Information about the versions:
```
sz: 2.1.12.2
hdf5: 1.10.7
gcc: 11.2.0
```

## To reproduce the error:
In case you want to reproduce the error, here some instructions.

I could run that on a python virtual environment with the following installation (no binary for h5py to link it to the proper hdf5).
```
python3 install h5py h5netcdf xarray --no-binary h5py
```

The code:
```python

# Imports
import xarray as xr
import numpy as np
import pandas as pd

# Encodings used for both cases

encoding_time_as_first_dimension = {'var': {'_FillValue': None,
                                            # Specify chunk sizes, in this case we have the time as the first dimension
                                            # so we use a slice of a single time-step to compress the data.
                                            'chunksizes': (1, 31, 360, 91),
                                            'compression': 32017,
                                            'compression_opts': (4,  # Dimensions
                                                                 0,  # Data type
                                                                 1,  # Sizes of the dimensions
                                                                 31,
                                                                 360,
                                                                 91,
                                                                 # Compression mode:
                                                                 1,
                                                                 # Tolerances packed as a 64-bit integer
                                                                 0,
                                                                 953267991,
                                                                 0,
                                                                 0)},
                                    }

encoding_time_as_last_dimension = {'var': {'_FillValue': None,
                                           'chunksizes': (31, 360, 91, 1),
                                           'compression': 32017,
                                           'compression_opts': (4,  # Dimensions
                                                                0,  # Data type
                                                                # Sizes of the dimensions:
                                                                31,
                                                                360,
                                                                91,
                                                                1,
                                                                # Compression mode (1 corresponding to REL):
                                                                1,
                                                                # Tolerances packed as a 64-bit integer
                                                                0,
                                                                953267991,
                                                                0,
                                                                0)},
                                   }


def create_xarray_dataset(time_is_first_dimension=False):
    # Create a synthetic dataset representing a 4D variable (3D + time)
    nx, ny, nz, t = 360, 91, 31, 5
    lon = np.linspace(-180, 180, nx)
    lat = np.linspace(-90, 90, ny)
    levels = np.array(range(nz))

    if time_is_first_dimension:
        data_size = (t, nz, nx, ny)
        var_dimensions = ["time", "level", "lon", "lat"]
    else:
        data_size = (nz, nx, ny, t)
        var_dimensions = ["level", "lon", "lat", "time"]

    # Select data type
    data_type = np.float32
    # Create some random data
    var_data = data_type(15 + 8 * np.random.randn(*data_size))

    ds = xr.Dataset(
        {
            "var": (var_dimensions, var_data),
        },
        # Set up the coordinates
        coords={
            "lon": lon,
            "lat": lat,
            "level": levels,
            "time": pd.date_range("2014-09-06", periods=t),
            "reference_time": pd.Timestamp("2014-09-05"),
        },
    )
    return ds


def try_encoding(encoding: dict, time_is_first_dimension=False, filename="test.nc"):
    """
    Try to save a file using xarray with the given encoding.
    """
    ds = create_xarray_dataset(time_is_first_dimension=time_is_first_dimension)

    # Save the dataset to disk using the provided encoding
    ds.to_netcdf(path=filename, encoding=encoding, engine="h5netcdf")
    print(f"\tWriting of file {filename} done")

    with xr.open_dataset(filename) as ds:
        for variable in ds.data_vars:
            print(f"\t\tReading {variable}")
            ds[variable].load()
    ds.close()
    del ds
    print(f"\tReading of file {filename} done")


def main():
    # Save the file without encoding
    print("############################\n")
    print("Saving the dataset without any encoding")
    try_encoding({}, filename="vanilla.nc")

    print("############################\n")
    print("Saving the dataset with SZ encoding with the time as the LAST dimension")
    # Save the file with encoding with the time as the last dimension
    try_encoding(encoding_time_as_last_dimension, time_is_first_dimension=False, filename="time_last.nc")

    print("############################")
    print("############################")
    print("############################")
    print("Saving the dataset with SZ encoding with the time as the FIRST dimension")
    # Save the file with encoding with the time as the first dimension
    try_encoding(encoding_time_as_first_dimension, time_is_first_dimension=True, filename="time_first.nc")


if __name__ == "__main__":
    main()

```

The output:

```
############################

Saving the dataset without any encoding
	Writing of file vanilla.nc done
		Reading var
	Reading of file vanilla.nc done
############################

Saving the dataset with SZ encoding with the time as the LAST dimension
	Writing of file time_last.nc done
		Reading var
	Reading of file time_last.nc done
############################
############################
############################
Saving the dataset with SZ encoding with the time as the FIRST dimension
	Writing of file time_first.nc done
		Reading var
Segmentation fault (core dumped)

```

**Comment by disheng222** [comment]
I have identified the reason for this bug. I will fix it soon. Thanks for
reporting this issue.

**Comment by orioltinto** [comment]
That's great, thanks!

**Comment by disheng222** [comment]
The bug is fixed. Please kindly note that the format of cd_values is changed, because the data type and dimensions are actually not needed. This information can be received based on hdf5's attributes. So, the only information needed about cd_values from users is the error configuration. I added a utility code in examples/ (called print_h5repack_args), which can help print the h5repack parameters (such as-f UD=32017,0,5,....). I also updated the user guide.

**Comment by disheng222** [comment]
More specifically, in your example, 
encoding_time_as_last_dimension = {'var': {'_FillValue': None,
                                           'chunksizes': (31, 360, 91, 1),
                                           'compression': 32017,
                                           'compression_opts': (4,  # Dimensions
                                                                0,  # Data type
                                                                # Sizes of the dimensions:
                                                                31,
                                                                360,
                                                                91,
                                                                1,
                                                                # Compression mode (1 corresponding to REL):
                                                                1,
                                                                # Tolerances packed as a 64-bit integer
                                                                0,
                                                                953267991,
                                                                0,
                                                                0)}, 
should be changed to : 
encoding_time_as_last_dimension = {'var': {'_FillValue': None,
                                           'chunksizes': (31, 360, 91, 1),
                                           'compression': 32017,
                                           'compression_opts': (
                                                                # Compression mode (1 corresponding to REL):
                                                                1,
                                                                # Tolerances packed as a 64-bit integer
                                                                0,
                                                                953267991,
                                                                0,
                                                                0)},

**Comment by orioltinto** [comment]
That's great! Thank you!
Is it possible to have a release with this change in it?

**Comment by orioltinto** [comment]
Much appreciated!
